[project]
authors = ["llango <724261350@qq.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "a mojo package to load environment variables from .env file."
name = "dotenv"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = "mojo test.mojo"

[dependencies]
max = ">=24.5.0,<25"
python = ">=3.8,==3.12"
