[workspace]
authors = ["llango<724261350@qq.com>"]
channels = [
    "https://conda.modular.com/max", 
    "conda-forge", 
    "https://repo.prefix.dev/modular-community", 
    "https://prefix.dev/mojo-force"
]
description = "a mojo package to load environment variables from .env file."
name = "dotenv"
platforms = ["linux-64"]
version = "0.1.3"


[tasks]
test = { cmd = "MOJO_PATH=$MOJO_PATH:$(pwd) mojo tests/test_main.mojo"}
build = "rattler-build build -r src -c https://prefix.dev/mojo-force -c https://repo.prefix.dev/modular-community -c https://conda.modular.com/max -c conda-forge --skip-existing=all"
publish = { cmd = "bash scripts/publish.sh", env = { PREFIX_API_KEY = "$PREFIX_API_KEY" } }

[dependencies]
mojo = ">=1.0.0b2"
python = ">=3.10,==3.12"
