# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "0.1.2"

package:
  name: "dotenv"
  version: 0.1.2

source:
  - path: .
  - path: ../LICENSE
  - path: ../tests/test_main.mojo

build:
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - pixi run mojo precompile dotenv
    - cp dotenv.mojoc ${PREFIX}/lib/mojo/dotenv.mojoc

requirements:
  run:
    - mojo >= 1.0.0b2

tests:
  - script:
      # commands to run to test the package. If any of the commands
      # returns with an error code, the test is considered failed.
      # if I don't copy everything into a test dir, pixi test runs the tests in the .pixi dir and fails :|
      - pixi run mojo precompile dotenv  # 打包
      - pixi run mojo install dotenv.mojoc  # 安装
      - pixi run mojo run tests/test_main.mojo  # 测试

    files:
      # Extra files to be copied to the test directory from the "work directory"
      source:
        - dotenv.mojoc
        - pixi.toml
        - test.mojo

about:
  homepage: https://github.com/llango/dotenv
  license: MIT
  license_file: LICENSE
  summary: a mojo package to load environment variables from .env file. https://github.com/llango/dotenv
  repository: https://github.com/llango/dotenv
