# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "0.1.0"

package:
  name: "dotenv"
  version: 0.1.0

source:
  - path: .
  - path: ../LICENSE
  - path: ../test.mojo

build:
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - magic run mojo package dotenv
    - cp dotenv.mojopkg ${PREFIX}/lib/mojo/dotenv.mojopkg

requirements:
  run:
    - max >= 24.5.0,<25

tests:
  - script:
      # commands to run to test the package. If any of the commands
      # returns with an error code, the test is considered failed.
      # if I don't copy everything into a test dir, mojo test runs the tests in the .magic dir and fails :|
      - magic run test

    files:
      # Extra files to be copied to the test directory from the "work directory"
      source:
        - dotenv.mojopkg
        - mojoproject.toml
        - test.mojo

about:
  homepage: https://github.com/llango/dotenv
  license: MIT
  license_file: LICENSE
  summary: a mojo package to load environment variables from .env file. https://github.com/llango/dotenv
  repository: https://github.com/llango/dotenv
